### ISSUE TITLE
Where is this option located?

### ISSUE THREAD

**Issue by GettingTechnicl** [shatyuka/PAYDAY2-Borderless-Windowed-Updated#1]
I unzipped this specifically where it says to... I do not see any option for borderless window. Please advise, thank you.

**Comment by shatyuka** [comment]
Sorry for the incomplete description. Actually this is a SuperBLT mod, you should install [SuperBLT](https://superblt.znix.xyz/) first. Have fun.

**Comment by GettingTechnicl** [comment]
I do have super blt, I still don't see the option in the menu near where fullscren/windowed option is. Is this located in a different menu somewhere? 

![image](https://user-images.githubusercontent.com/56567784/99625697-6b127f00-29f6-11eb-97fa-18110d854e1a.png)

Mod options only shows language selection

**Comment by shatyuka** [comment]
@GettingTechnicl  Could you provide the log plus with your system infermation?

**Comment by GettingTechnicl** [comment]
System info
--------------
Ryzen 9 3950x
32GB ram
Nvidia 2070super

Attached log file. 
[2020_11_18_log.txt](https://github.com/shatyuka/PAYDAY2-Borderless-Windowed-Updated/files/5570350/2020_11_18_log.txt)

**Comment by GettingTechnicl** [comment]
wow, looked at log file after uploading, appears I had another folder inside the main borderless windowed folder. whoops. 

This works perfectly, my apologies for re-opening.
