### ISSUE TITLE
Any requierements? Does not work

### ISSUE THREAD

**Issue by DMLON** [shatyuka/PAYDAY2-Borderless-Windowed-Updated#2]
Hello there, i tried this plugin with no success, i unzipped the zip to mods having WINSOCK32 (Super BTL) and there was no option?
Is the plugin even compiled?
Tried compiling it and placed the .dll in mods and in payday 2 root folder, nothing

**Comment by shatyuka** [comment]
For general user, you are not required to compile the source code. You only need to download the last release and unzip it to `mods` directory.
The dir tree should show like this:
```
|-- PAYDAY 2
    |-- assets
    |-- Maps
    |-- mods
    |   |-- Borderless Windowed Updated
    |       |-- loc
    |       |-- Borderless Windowed Updated.dll
    |       |-- Borderless Windowed Updated.lua
    |       |-- ...
    |-- ...
    |-- WSOCK32.dll
```
Additional information: https://modworkshop.net/mod/27683

**Comment by DMLON** [comment]
My bad, i got to the github page from google, didn't know it was from modworkshop hahaha.
Thank you

**Comment by shatyuka** [comment]
This repo only contains the native source code. However, the zip archive in release is a full-functional mod.
