### ISSUE TITLE
Option doesn't save, and text is errored

### ISSUE THREAD

**Issue by Bneboy** [shatyuka/PAYDAY2-Borderless-Windowed-Updated#3]
Hello, I found this mod on modworkshop. I noticed that I have to change the option to borderless fullscreen every time I boot up the game, and that the language text has lots of errors in it in the settings.

I read the comments, and many others have the same issue, but it is still persistent. Other than that, it works fine.

**Comment by shatyuka** [comment]
Try version v1.4

**Comment by jotsar** [comment]
> 
> 
> Try version v1.4

it still doesnt work

**Comment by shatyuka** [comment]
@jsmoment More information needed. Game version, SuperBLT version, enabled mods, language of your system and game. And log file PLZ.

**Comment by jotsar** [comment]
> 
> 
> @jsmoment More information needed. Game version, SuperBLT version, enabled mods, language of your system and game. And log file PLZ.

OS: Windows 10
Game version: i don't know how to check it, but i'm running the latest steam release which at the time is update 209.1
SuperBLT version: 1.3.1
Language: english (both system and game)
Mods:
![image](https://user-images.githubusercontent.com/75227863/130283047-49bd4353-099a-44a0-b6b2-384ec2b98b84.png)
SuperBLT log:
[2021_08_20_log.txt](https://github.com/shatyuka/PAYDAY2-Borderless-Windowed-Updated/files/7023682/2021_08_20_log.txt)

editing because the superblt log didnt get attached

**Comment by Bneboy** [comment]
I can't speak for @jsmoment , but 1.4 works for me. Many thanks

**Comment by shatyuka** [comment]
@jsmoment The log looks alright. Have you tried disable all mods except this one?

**Comment by jotsar** [comment]
> 
> 
> @jsmoment The log looks alright. Have you tried disable all mods except this one?

alright, it worked. do you know what mod it might be conflicting with?
edit: enabled them one by one and it was my dlc unlocker. is there any way to fix this? i don't have the money to buy the new dlcs.

**Comment by shatyuka** [comment]
> > @jsmoment The log looks alright. Have you tried disable all mods except this one?
> 
> alright, it worked. do you know what mod it might be conflicting with?
> edit: enabled them one by one and it was my dlc unlocker. is there any way to fix this? i don't have the money to buy the new dlcs.

I'll look into it.

**Comment by shatyuka** [comment]
@jsmoment Fixed, try version v1.5

**Comment by jotsar** [comment]
> 
> 
> @jsmoment Fixed, try version v1.5

thank you. it works now.
