### ISSUE TITLE
Random crashes when focusing back on Payday 2 on Linux using Proton

### ISSUE THREAD

**Issue by ghost** [shatyuka/PAYDAY2-Borderless-Windowed-Updated#5]
Hello,
I've been having this issue where when I unfocus Payday 2 window on x11 focusing back on it sometimes doesn't cause an immediate crash but other times it does.
I suspect this is not a problem with the Borderless Windowed plugin because Payday 2 already has the same issue (well not randomly) for full screen gaming.
When I use windowed mode with borders on Payday 2 I don't have this issue
Would still love to hear feedback on this issue.

**Comment by GamerD4rker** [comment]
It's a linux problem not a mod problem.

**Comment by ghost** [comment]
It's more of a linux problem
